create table if not exists public.gambclub_visitor_logs (
  id bigint generated by default as identity primary key,
  site text not null default 'gambclub.com',
  visitor_type text not null check (visitor_type in ('human','bot')),
  city text,
  country text,
  country_code text,
  created_at timestamptz not null default now(),
  user_agent text,
  referrer text
);

alter table public.gambclub_visitor_logs enable row level security;

drop policy if exists "GambClub insert visitors" on public.gambclub_visitor_logs;
create policy "GambClub insert visitors"
  on public.gambclub_visitor_logs for insert
  to anon, authenticated
  with check (site = 'gambclub.com');

drop policy if exists "GambClub read visitors" on public.gambclub_visitor_logs;
create policy "GambClub read visitors"
  on public.gambclub_visitor_logs for select
  to anon, authenticated
  using (site = 'gambclub.com');

drop policy if exists "GambClub delete visitors" on public.gambclub_visitor_logs;
create policy "GambClub delete visitors"
  on public.gambclub_visitor_logs for delete
  to anon, authenticated
  using (site = 'gambclub.com');
